title: Bol.com documentation
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Bol.com
email: contact@bol.com
avatar: assets/images/avatar.jpg


remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
